[package]
name = "peanut"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
base64 = "0.21.5"
crypter = { version = "0.2.0", features = ["stream"] }
hex = "0.4.3"
sha2 = "0.10.8"
zstd = "0.13.0"
